spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
              - Path=/admin/categories/**,/categories/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/compilations/**,/events/**
server:
  port: 8080
